const mongoose = require('mongoose');
const Certificate = require('./models/Certificate');

const initialCertificates = [
  {
    certificateId: 'SSS-017',
    studentName: 'R. Harsha vardhan',
    studentEmail: 'harshavardhan.r@aliet.ac.in',
    course: 'Full Stack Development using MERN Stack',
    collegeName: 'Andhra Loyola Institute of Engineering and Technology (ALIET)',
    rollNumber: '25HP1A1229',
    department: 'IT',
    year: '2nd Year',
    issuedDate: new Date('2026-08-10'),
    status: 'active',
    issuedBy: 'CHANDRA SEKHAR UPPU - FOUNDER & CEO SSS',
  },
  {
    certificateId: 'SSS-018',
    studentName: 'K. Hemanth kumar',
    studentEmail: 'hemanthkumar.k@aliet.ac.in',
    course: 'Full Stack Development using MERN Stack',
    collegeName: 'Andhra Loyola Institute of Engineering and Technology (ALIET)',
    rollNumber: '25HP1A1230',
    department: 'IT',
    year: '2nd Year',
    issuedDate: new Date('2026-08-10'),
    status: 'active',
    issuedBy: 'CHANDRA SEKHAR UPPU - FOUNDER & CEO SSS',
  },
  {
    certificateId: 'SSS-019',
    studentName: 'Y. Siddhartha',
    studentEmail: 'siddhartha.y@aliet.ac.in',
    course: 'Full Stack Development using MERN Stack',
    collegeName: 'Andhra Loyola Institute of Engineering and Technology (ALIET)',
    rollNumber: '25HP1A1246',
    department: 'IT',
    year: '2nd Year',
    issuedDate: new Date('2026-08-10'),
    status: 'active',
    issuedBy: 'CHANDRA SEKHAR UPPU - FOUNDER & CEO SSS',
  },
  {
    certificateId: 'SSS-020',
    studentName: 'B. Akhil',
    studentEmail: 'akhil.b@aliet.ac.in',
    course: 'Full Stack Development using MERN Stack',
    collegeName: 'Andhra Loyola Institute of Engineering and Technology (ALIET)',
    rollNumber: '25HP1A1225',
    department: 'IT',
    year: '2nd Year',
    issuedDate: new Date('2026-08-10'),
    status: 'active',
    issuedBy: 'CHANDRA SEKHAR UPPU - FOUNDER & CEO SSS',
  },
  {
    certificateId: 'SSS-021',
    studentName: 'Sk. Rabiya',
    studentEmail: 'rabiya.sk@aliet.ac.in',
    course: 'Full Stack Development using MERN Stack',
    collegeName: 'Andhra Loyola Institute of Engineering and Technology (ALIET)',
    rollNumber: '25HP1A1214',
    department: 'IT',
    year: '2nd Year',
    issuedDate: new Date('2026-08-10'),
    status: 'active',
    issuedBy: 'CHANDRA SEKHAR UPPU - FOUNDER & CEO SSS',
  },
  {
    certificateId: 'SSS-022',
    studentName: 'G. Harika',
    studentEmail: 'harika.g@aliet.ac.in',
    course: 'Full Stack Development using MERN Stack',
    collegeName: 'Andhra Loyola Institute of Engineering and Technology (ALIET)',
    rollNumber: '25HP1A1206',
    department: 'IT',
    year: '2nd Year',
    issuedDate: new Date('2026-08-10'),
    status: 'active',
    issuedBy: 'CHANDRA SEKHAR UPPU - FOUNDER & CEO SSS',
  },
  {
    certificateId: 'SSS-023',
    studentName: 'T. Shalini',
    studentEmail: 'shalini.t@aliet.ac.in',
    course: 'Full Stack Development using MERN Stack',
    collegeName: 'Andhra Loyola Institute of Engineering and Technology (ALIET)',
    rollNumber: '25HP1A1217',
    department: 'IT',
    year: '2nd Year',
    issuedDate: new Date('2026-08-10'),
    status: 'active',
    issuedBy: 'CHANDRA SEKHAR UPPU - FOUNDER & CEO SSS',
  },
  {
    certificateId: 'SSS-024',
    studentName: 'B. Dil Rani',
    studentEmail: 'dilrani.b@aliet.ac.in',
    course: 'Full Stack Development using MERN Stack',
    collegeName: 'Andhra Loyola Institute of Engineering and Technology (ALIET)',
    rollNumber: '25HP1A1204',
    department: 'IT',
    year: '2nd Year',
    issuedDate: new Date('2026-08-10'),
    status: 'active',
    issuedBy: 'CHANDRA SEKHAR UPPU - FOUNDER & CEO SSS',
  },
  {
    certificateId: 'SSS-025',
    studentName: 'B. Mahitha',
    studentEmail: 'mahitha.b@aliet.ac.in',
    course: 'Full Stack Development using MERN Stack',
    collegeName: 'Andhra Loyola Institute of Engineering and Technology (ALIET)',
    rollNumber: '25HP1A1211',
    department: 'IT',
    year: '2nd Year',
    issuedDate: new Date('2026-08-10'),
    status: 'active',
    issuedBy: 'CHANDRA SEKHAR UPPU - FOUNDER & CEO SSS',
  },
  {
    certificateId: 'SSS-028',
    studentName: 'D. Sai Vennela',
    studentEmail: 'saivennela.d@aliet.ac.in',
    course: 'Full Stack Development using MERN Stack',
    collegeName: 'Andhra Loyola Institute of Engineering and Technology (ALIET)',
    rollNumber: '25HP1A1216',
    department: 'IT',
    year: '2nd Year',
    issuedDate: new Date('2026-08-10'),
    status: 'active',
    issuedBy: 'CHANDRA SEKHAR UPPU - FOUNDER & CEO SSS',
  },
  {
    certificateId: 'SSS-029',
    studentName: 'K. Teja Sri',
    studentEmail: 'tejasri.k@aliet.ac.in',
    course: 'Full Stack Development using MERN Stack',
    collegeName: 'Andhra Loyola Institute of Engineering and Technology (ALIET)',
    rollNumber: '25HP1A1220',
    department: 'IT',
    year: '2nd Year',
    issuedDate: new Date('2026-08-10'),
    status: 'active',
    issuedBy: 'CHANDRA SEKHAR UPPU - FOUNDER & CEO SSS',
  },
];

const autoSeedCertificates = async () => {
  try {
    for (const cert of initialCertificates) {
      await Certificate.updateOne(
        { certificateId: cert.certificateId },
        { $setOnInsert: cert },
        { upsert: true }
      );
    }
    console.log('✅ Student certificates auto-seeded successfully');
  } catch (err) {
    console.error('❌ Auto-seed certificates error:', err.message);
  }
};

module.exports = { initialCertificates, autoSeedCertificates };
